services:
  diff-train:
    container_name: diff-train
    build: .
    volumes:
      - ./:/root/working
    # GPU support: https://docs.docker.com/compose/how-tos/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
