services:
  diff-train:
    container_name: diff-train
    build: .
    image: nhf-diff-train
    volumes:
      - ./:/root/working
    ports:
      - "127.0.0.1:1234:1234" # jupyter
      - "127.0.0.1:8887:8887" # gradio
    # GPU support: https://docs.docker.com/compose/how-tos/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
